image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt

test:
  variables:
	BISMARCK_HOME: '/builds/AnyKeyShik/Bismarck'
    BISMARCK_LOGLEVEL: 'INFO'
  script:
    - python3 -m unittest discover -s tests -t .

